# Generated by Django 4.1.7 on 2023-02-23 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('eta', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('Complete', 'Complete')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.CharField(max_length=50)),
                ('field_updated', models.CharField(max_length=20)),
                ('last_modified', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.task')),
            ],
        ),
    ]
