# Generated by Django 4.1.7 on 2023-02-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('eta', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('InReview', 'InReview'), ('Complete', 'Complete')], default='Pending', max_length=50)),
            ],
        ),
    ]
